### ISSUE TITLE
Foreground color and alpha blending results

### ISSUE THREAD

**Issue by vishalnayak108** [yucornetto/MGMatting#14]
Hi,
The mask I am getting is so accurate but when I am doing alpha blending on mask image to create image with no ackgound the results are not good. Can you please help me in this?

**Comment by yucornetto** [comment]
Hi, I think directly using the image as the foreground may not be optimal, that's why we use random alpha blending to train a network predicting foreground color. You can start with using traditional methods such as closed-form matting to predict a foreground maybe to see if it works.

**Comment by mstarget** [comment]
I have a dimension mismatch error when FORWARD (), do you know why? Can you help me?
`raceback (most recent call last):
  File "./main.py", line 105, in <module>
    main()
  File "./main.py", line 73, in main
    trainer.train()
  File "/code/MGMatting/code-base/trainer.py", line 306, in train
    pred = self.G(image, mask)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/code/MGMatting/code-base/networks/generators.py", line 24, in forward
    inp = torch.cat((image, guidance), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 1280 and 1920 (The offending index is 0)
`

**Comment by mstarget** [comment]
I have a dimension mismatch error when FORWARD (), do you know why? Can you help me?

`Traceback (most recent call last):
  File "./main.py", line 105, in <module>
    main()
  File "./main.py", line 73, in main
    trainer.train()
  File "/code/MGMatting/code-base/trainer.py", line 306, in train
    pred = self.G(image, mask)
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File /anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/code/MGMatting/code-base/networks/generators.py", line 24, in forward
    inp = torch.cat((image, guidance), dim=1)
RuntimeError: Sizes of tensors must match except in dimension 2. Got 1280 and 1920 (The offending index is 0)
`

**Comment by ousinkou** [comment]
@yucornetto Any plan to release the random alpha blending training code?

**Comment by mexicantexan** [comment]
@yucornetto Any plan to release the random alpha blending training code?
